### ISSUE TITLE
print-doc and print-ns-doc errors

### ISSUE THREAD

**Issue by ChipNowacek** [phillord/tawny-owl#47]
I think they have trouble with the ontology itself. Here's the [code that fails for me](https://github.com/ChipNowacek/learning-tawny/blob/print-ns-doc-error/src/learning_tawny/this-and-that.clj). I'll work around it.

**Comment by phillord** [comment]
Thanks! This is fixed on version-1 and version-2 branches. I'm not ready to merge either of these to master yet, am afraid!
