### ISSUE TITLE
single/multiple frame rule inconsistent

### ISSUE THREAD

**Issue by ChipNowacek** [phillord/tawny-owl#53]
Seems I can add multiple `:comment` frames to classes but not to ontologies. Both fail:
`(defontology <ont> :comment "this" "that")` 
`(refine <ont> :comment "another comment")`
Consistency seems appropriate and natural given OWL allows multiple in both situations.

**Comment by ChipNowacek** [comment]
Wrong. I'm revising the last comment.

**Comment by ChipNowacek** [comment]
Any suggestions for work arounds?

**Comment by ChipNowacek** [comment]
Sorry. I found `tawny.owl/add-ontology-comment` and will use its innards.

**Comment by phillord** [comment]
It''s a bug, I agree. I will fix it.
