### ISSUE TITLE
:label not allowed on ontology

### ISSUE THREAD

**Issue by ChipNowacek** [phillord/tawny-owl#54]
Can add it with `:annotation (label "yada yada")`

Similar to #53, really a matter of consistency and OWL support. `:label` looks better.

**Comment by phillord** [comment]
I'm not convinced by that consistency is so important here. Entities need a label, but it's not so clear to me that ontologies do, so using the long hand is not a big thing.

Still, it's easy to add. I'll do so or will accept a PR.

**Comment by ChipNowacek** [comment]
Given the admittedly controversial nature of the matter, I'll send a PR when I can.
