### ISSUE TITLE
Thoughts re: tawny-owl and immutability, monotonicity, and persistence

### ISSUE THREAD

**Issue by danlentz** [phillord/tawny-owl#6]
I have been looking at tawny-owl while getting my feet wet with clojure in general and it looks quite nice.  I am also interested in the possibility of integrating tawny's concepts with those that are compatible with a persistence solution -- datomic being the principal target of interest, as it is already quite a nice triple-store.  Naturally, there are some aspects of tawny which currently conflict with the requirements of such an idea as I see them.  I was wondering if there were existing thoughts from the tawny developers (community?) to this end and if so I'd be very interested to hear them.  

At last read of the documentation, there seems to be a "throw our hands up" sort of "we don't do that" kind of feel to the questions related to immutability.  However, coming from a common-lisp background I have worked with a very interesting package http://github.com/lisp/de.setf.resource which implements a very interesting model for approaching these issues and I wonder what is the level of enthusiasm that some of the concepts it proposes may also prove to be quite relevant with regards to clojure and tawny-owl.

There are a number of areas suitable for discussion, but IMO, The central technical matters relate to the notion of the resource "life-cycle" which is a concept that is shared with other RDF persistence software, namely Spirograph which is a somewhat more well known solution in the Ruby space.  Also Id mention as prior art the LSW project which focuses on the owl<->triples bijection by means of rulesets defined in SWRL.... But I don't want to get ahead of myself here, so perhaps it would be most productive to focus on the first two paragraphs, above, and leave this one be, for now. :)

Regards,
Dan

**Comment by ChipNowacek** [comment]
I carefully read the [datomic free license](https://my.datomic.com/datomic.com/datomic-free-edition-license.html). It seems designed for this kind of work.

Did you get a chance to look at Dan's library?

**Comment by phillord** [comment]
I haven't I am afraid, nor have I used datomic, but yes, it has a similar purpose.
