### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by phillord** [phillord/tawny-owl#62]
I plan to release 2.0 in a short while. Any blockers here.

**Comment by bzg** [comment]
I'm still using tawny-owl and enjoying it a lot. Is there anything I should test?

I will try to proofread the documentation a little bit to catch typos.

**Comment by phillord** [comment]
Difficult to say really. I'm working on the long missing manual, and that will throw up a few things. I'm not planning on adding any new functionality now. Probably I'll miss a few bugs, so I would be unsurprised to do a minor release shortly after.

**Comment by dfornika** [comment]
Can this issue be closed, since v2.0 has been released?
