### ISSUE TITLE
Pizza ontology tutorial: "unable to resolve symbol: functional"

### ISSUE THREAD

**Issue by mathpunk** [phillord/tawny-owl#63]
I am interested in learning about designing ontologies, and I was following the example of the pizza ontology in your "Getting Started." 

When I try to evaluate something like:

```
(ns ontologies.pizza
  (:require [tawny.owl :as owl]))

(owl/declare-classes
 Pizza
 PizzaBase)

(owl/defoproperty hasIngredient)

(owl/defoproperty hasBase
  :subpropertyof hasIngredient
  :characteristics owl/functional
  :range PizzaBase
  :domain Pizza)
```
...I get `Unable to resolve symbol: functional in this context`.

I think that `functional` is getting defined [here](https://github.com/phillord/tawny-owl/blob/a8fc8300481a1e033a3811ccda54e552392d1689/src/tawny/owl.clj#L2048). As an experiment I tried replacing `functional` with `irreflexive` and got the same result, so I hazard that none of the functions named in that `do` form are getting declared, or at least are not getting declared non-privately.

**Comment by phillord** [comment]
Ah, sorry, it should be `:functional` with a colon?

I've been working on replacing those documents with a proper tutorial, but alas, have got rather stalled. The problem is with markdown I cannot sanely test that my code actually works. Need to fix this.

**Comment by mathpunk** [comment]
Hm, that yields----

```
(owl/defoproperty hasBase
                           :subpropertyof hasIngredient
                           :characteristics :functional
                           :range PizzaBase
                           :domain Pizza)
IllegalArgumentException Expected only keys (:ontology :subpropertychain :subchain :sub :inverse :disjoint :super :characteristic :label :subproperty :comment :domain :annotation :range :equivalent); Got ((#object[uk.ac.manchester.cs.owl.owlapi.OWLClassImpl 0x16c0054d "<http://www.ncl.ac.uk/pizza#PizzaBase>"]) (:subpropertyof #object[uk.ac.manchester.cs.owl.owlapi.OWLObjectPropertyImpl 0x1d1b707b "<http://www.ncl.ac.uk/pizza#hasIngredient>"] :characteristics :functional))  tawny.util/check-keys (util.clj:99)
```

**Comment by phillord** [comment]
Oh dear. This stuff does need updating doesn't it.

`(defoproperty hasBase :super hasIngredient :characteristics :functional)`

**Comment by phillord** [comment]
I'll update these and https://github.com/phillord/tawny-pizza as soon as I can. I am hoping to release 2.0 fairly soon, but these need fixing.

**Comment by dfornika** [comment]
@phillord It looks like this was resolved. Can the issue be closed?

**Comment by phillord** [comment]
Indeed! Thanks
