### ISSUE TITLE
memorise: Wrong number of args (0) passed to: tawny.owl/ontology-options

### ISSUE THREAD

**Issue by dfornika** [phillord/tawny-owl#74]
The `tawny.memorize/memorise` function seems to be failing with the error message:

```
Execution error (ArityException) at tawny.memorise/fetch-remembered-entities (memorise.clj:83).                                                            
Wrong number of args (0) passed to: tawny.owl/ontology-options
```

`memorise` calls [`fetch-remembered-entities`](https://github.com/phillord/tawny-owl/blob/079028b7547743a36384650981ea068849aac53e/src/tawny/memorise.clj#L78-L84), which calls [`tawn.owl/ontology-options`](https://github.com/phillord/tawny-owl/blob/079028b7547743a36384650981ea068849aac53e/src/tawny/owl.clj#L698-L708) with no arguments, but `ontology-options` takes a single argument.

**Comment by phillord** [comment]
Does this work?

**Comment by dfornika** [comment]
Hi @phillord thanks for addressing this issue. It might take me some time to find the development environment I was using when I ran into this issue, so I may not be able to quickly confirm that it works for me. 

But it certainly looks like a reasonable fix so if it's working on your system then please go ahead with merging it even if I'm not able to confirm.

**Comment by dfornika** [comment]
@phillord Ok, I can report back now that this does fix my issue.

I have this repo for a tawny version of the Sequence Ontology:

https://github.com/dfornika/tawny-so

I read the ontology here:

https://github.com/dfornika/tawny-so/blob/master/src/tawny/obo/so.clj

...and used your updated code to memorise the ontology here:

https://github.com/dfornika/tawny-so/blob/master/src/tawny/obo/so_memorise.clj

**Comment by phillord** [comment]
Thanks for testing! This is one of the hardest bits to test, so it's good to get confirmation.
