### ISSUE TITLE
InstaREPL: "Security Manager is deprecated"

### ISSUE THREAD

**Issue by Trevoke** [phillord/tawny-owl#81]
Hello!
I'm beginning to go through the take-wing manual. I toggled the `InstaREPL` and this warning occurred to the left of the few lines of Clojure I have:

![image](https://github.com/user-attachments/assets/8c4758e8-8c2a-44fb-8cbf-5d1278f34707)
![image](https://github.com/user-attachments/assets/121d2de5-4e3c-4491-9790-31cac53cbd6f)

It's obviously not a blocker but I thought you might want to know :)

**Comment by phillord** [comment]
This is more of a problem for nightlight than tawny. I think that nightlight is not in active development any more. You might want to move over to a different editor.
